apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: "kubernetes-services"
        kubernetes_sd_configs:
          - role: endpoints
      - job_name: "api-gateway"
        static_configs:
          - targets: ["api-gateway.ai-devops.svc.cluster.local:8080"]
