apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-sa
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: platform-role
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: [""]
  resources: ["pods", "events", "services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: platform-rb
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: platform-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: platform-role
